baseURL = "http://fauzanjantung.github.io/"
title = "Fauzan Fathurrahman"
googleAnalytics = "UA-123-456-789"
theme = "github-style"
copyright = "Â© 2019. Theme by <a href=\"https://github.com/MeiK2333/github-style\"><span>github-style</span></a>"

[params]
  author = "Fauzan"
  description = "Moon Pie"
  github = "https://github.com/fauzanjantung"
  twitter = "https://twitter.com/superjantung"
  email = "fauzan08fauzan@gmail.com"
  utterances = "example/example.github.io"
  avatar = "http://fauzanjantung.github.io/images/avatar.png"
  url = "http://fauzanjantung.github.io"
  keywords = "blog, google analytics"